platform :ios, '6.0' 

pod 'SHSegueBlocks'
pod 'SHBarButtonItemBlocks'
pod 'SHFastEnumerationProtocols', :git => "https://github.com/PodFactory/SHFastEnumerationProtocols", :branch => "master"
target :ExampleTests do
  pod 'SHTestCaseAdditions', :git => "https://github.com/seivan/SHTestCaseAdditions"
  pod "KIF-next"
end



